services:
  master:
    image: pest-mod-res-ensi
    container_name: master
    entrypoint: ["/bin/bash", "/app/entrypoint_master.sh"]
    environment:
      - NOMBRE_MODELO_PEST=${NOMBRE_MODELO_PEST:-mod_res_ensi.pst}
      - EJECUTABLE_MASTER=${EJECUTABLE_MASTER:-pest_hp}
      - BUCKET_NAME=${BUCKET_NAME:-312019940349-pest-mod-res-ensi-west-2}
      - PEST_PORT=${PEST_PORT:-4004}
    ports:
      - "4004:4004"
    networks:
      - mi_red

  agente1:
    image: pest-mod-res-ensi
    container_name: agente1
    entrypoint: ["/bin/bash", "/app/entrypoint_agent.sh"]
    environment:
      - MASTER_HOST=master
      - NOMBRE_MODELO_PEST=${NOMBRE_MODELO_PEST:-mod_res_ensi.pst}
      - EJECUTABLE_AGENTE=${EJECUTABLE_AGENTE:-agent_hp}
      - PEST_PORT=${PEST_PORT:-4004}
    networks:
      - mi_red

networks:
  mi_red:
    driver: bridge